name: Backend Docker Build & Deploy

on:
  push:
    paths:
      - 'backend/**'   # This will trigger the workflow only for changes inside the 'backend' directory
  pull_request:
    paths:
      - 'backend/**'   # This ensures the workflow triggers on PRs for the 'backend' directory
  workflow_dispatch:   # This enables manual trigger of the workflow for debugging.

jobs:
  build:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image for Backend
        run: |
          cd backend
          docker build -t musiclify-backend:latest .

      - name: Stop and Remove Old Container
        run: |
          docker stop musiclify-backend-container || true
          docker rm musiclify-backend-container || true
          docker ps -a  # Log the status of all containers for debugging
      
      - name: Run New Container
        run: docker run -d --name musiclify-backend-container -p ${{ secrets.PORT_NUMBER }}:${{ secrets.PORT_NUMBER }} -e ${{ secrets.SPOTIFY_CLIENT_ID }} -e ${{ secrets.FRONTEND_URL }} musiclify-backend
